### ISSUE TITLE
Add Pipijing Whale Support

### ISSUE THREAD

**Issue by qdot** [buttplugio/buttplug-js#108]
Add support for the Pipijing Whale. C# implementation at https://github.com/buttplugio/buttplug-csharp/blob/master/Buttplug.Server/Bluetooth/Devices/LiBo.cs

**Comment by bnm12** [comment]
Link is dead after the move, new link is: https://github.com/buttplugio/buttplug-csharp/blob/master/Buttplug/Server/Bluetooth/Devices/LiBo.cs

**Comment by qdot** [comment]
buttplug-js will soon be part of buttplug-wasm in https://github.com/buttplugio/buttplug-rs-ffi, closing this bug as it relates to implementation that will be taken care of in buttplug-rs.
