### ISSUE TITLE
Add support for multiple motors to WeVibe

### ISSUE THREAD

**Issue by qdot** [buttplugio/buttplug-js#110]
Some WeVibe products have dual motor support. See https://github.com/buttplugio/buttplug-csharp/blob/master/Buttplug.Server/Bluetooth/Devices/WeVibe.cs

**Comment by bnm12** [comment]
Link is dead after the move new link: https://github.com/buttplugio/buttplug-csharp/blob/master/Buttplug/Server/Bluetooth/Devices/WeVibe.cs

**Comment by qdot** [comment]
Duplicates #151, which was fixed a while ago.
