### ISSUE TITLE
Add UFO SA support

### ISSUE THREAD

**Issue by qdot** [buttplugio/buttplug-js#116]
See https://github.com/buttplugio/buttplug-csharp/blob/master/Buttplug.Server/Bluetooth/Devices/VorzeSA.cs. Really only needs to add command format change (device choice) and extra device name.

**Comment by blackspherefollower** [comment]
Was this fixed by 863a8aac21e18d131a20712adc7db1d6d69d7c06

**Comment by qdot** [comment]
Yup.
