### ISSUE TITLE
ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by Sir-Prise** [buttplugio/buttplug-js#223]
I used `npm install buttplug` to use the library on a website.

While Node has Buffer included, browsers have not, which causes the error `ReferenceError: Buffer is not defined`.

My workaround was to `npm install buffer` and add this line to my script:
```ts
(window as any).Buffer = require('buffer').Buffer;
```

But I think Buffer should be a real dependency of this library and every usage of Buffer should use the import.

**Comment by qdot** [comment]
buttplug-js will soon be part of buttplug-wasm in https://github.com/buttplugio/buttplug-rs-ffi, closing this bug as it relates to implementation that will be taken care of in buttplug-rs.
