### ISSUE TITLE
Clockwise behavior for Rotation command

### ISSUE THREAD

**Issue by aglaia-resident** [buttplugio/buttplug-js#233]
**Describe the bug**
If i send this command:
`
SendRotateCmd(0.5, true);
`
the dildo turns clockwise.
Then, just after, i send the exact same command again:
`
SendRotateCmd(0.5, true);
`
The dildo change the rotation direction. However, it should just keep rotating at same speed and same rotation direction.
If i just change the speed and keep clocwise true:
`
SendRotateCmd(0.8, true);
`
The dildo will speed up, but again, the rotation direction will change again.

=> Anytime the clockwise parameter is true, the rotation direction is changing.
Oppositely, if clockwise is false, it will never change the rotation direction.

**Expected behavior**
If clockwise true it should turn in a rotation direction. If false it should turn in the opposite direction.

**Additional context**
Tested with Lovense Nora 137.

To see this bug, just use the playground:
https://playground.buttplug.world/
with "Connect in browser"
Put the slider somewhere on the right side of the Rotation Control slider. Then move it a little bit, staying on the right side: the rotation direction will change. Then move it to the left side: the rotation direction will NOT change.

**Comment by qdot** [comment]
Reopening this repo but killing the server impl, so this bug is no longer valid.
