### ISSUE TITLE
ButtplugClientDevice linearAttributes issue

### ISSUE THREAD

**Issue by mnh86** [buttplugio/buttplug-js#247]
**Describe the bug**
- Using buttplug-js `v3.1.1` with Intiface central `v2.3.0` and a device configuration with a Linear axis.
- `ButtplugClientDevice::linearAttributes` getter not returning data when `messageAttributes.LinearCmd` has data.

See https://github.com/buttplugio/buttplug-js/blob/3.1.1/src/client/ButtplugClientDevice.ts#L211-L213

Potential fix to rename line 212 from `this.messageAttributes.RotateCmd` to `this.messageAttributes.LinearCmd` .

**Comment by qdot** [comment]
Fixed in v3.2, finally.
