### ISSUE TITLE
Expose PeripheralId and technical device names

### ISSUE THREAD

**Issue by heavyrubberslave** [buttplugio/buttplug-js#259]
I don't know if it's possible, but I saw in the Intiface that there's a PeripheralId which I would expect to be a persistent and unique ID for the same device.

Currently there's only access to the index which is a bit tricky to identify a device uniquely, as devices can be removed and re-paired and get a new index assigned. It would be great to detect an earlier detected device again based on a persistent ID.

I also saw that Intiface has something like a "technical device name". In my case it's `lovense:P`(Edge) and `lovense:Z` (Hush). Any chance to make them accessible through the websocket server as well? This would help a lot to deal with the devices in other applications.

**Comment by qdot** [comment]
Indexes are static per device, managed by Intiface, so they're basically reliable at this point. PeripheralIds are unique per user and therefore expose user identifiable information, so we do not expose those to the client.

**Comment by drone4770** [comment]
Hi @qdot, 
I am using intiface-engine and it doesn't seem to be any retention of the id between restarts. 
Ids always start from 0 with first paired device after application start, so we have to pair them in the same order to have them keep their id. 
It leaves us with only the name as an identifier from time to time, but it prevents us from having the same device more then once.
Are we missing something?

**Comment by qdot** [comment]
@drone4770 Ah, ok, should've been a bit more clear. At the moment, ID persistence is a feature of intiface *central*, not intiface engine. The user configuration management is build in the top layer of the stack.

I'm currently rebuilding the config system to be easier to work with, at which point I can maybe look at pushing that feature back into engine.
