### ISSUE TITLE
Server and client in JavaScript/TypeScript (Node.js) with React-Native for mobile applications

### ISSUE THREAD

**Issue by th3-sh0w3r** [buttplugio/buttplug-js#261]
Hello,

I'm currently building a mobile only application with react-native for iOS and Android. I can access the connected Bluetooth Devices and now I'm wondering how I can setup an embedded server in JavaScript, because I don't want to use Intiface Central.

Can I just create my own WebSocket and send the "data" to the Buttplug.io Client (which would be the application itself)?
Or what would be the best solution in my case? I don't mind using libraries or something else, I just don't want a second application or App.

**Comment by qdot** [comment]
You can't easily do this with our codebase. We don't currently have a react native solution for the device server.

**Comment by th3-sh0w3r** [comment]
Is there maybe a different mobile framework that works with your codebase (doesn‘t matter which language) as server and client?

**Comment by qdot** [comment]
Depends on your code licensing. We have a flutter setup (that is built specifically for Central and may not be very easy to use), but it's dual licensed GPL or proprietary. If you're looking to close source and/or sell your app, we'd need to discuss licensing and contract terms.

**Comment by th3-sh0w3r** [comment]
The app should only react as bridge between a webserver and a device. We just don't want that the user has to download something external and make it as easy as possible for the user to connect to a device. So the app will be free for everyone.

Also I tried the Intiface Central App on my iOS with Faptap.net, but it did not work because the iOS websocket is for unknown reasons unsecure and uses ws:// instead of wss://
