### ISSUE TITLE
GUI component for connecting

### ISSUE THREAD

**Issue by stephanbogner** [buttplugio/buttplug-js#262]
Not sure if this fits here as this library is not about GUIs, but it would be interesting to hear your opinion on it.

**Connecting is fairly complicated due to many cases that have to be covered:**
You have to give an option to connect with Intiface or web bluetooth, check if web bluetooth is available, show search state, once connected show that state, give an option to test the device, what about multiple devices, ...

→ Take the fun out of trying things out

Of course this is mainly due to JS, connected devices and the browser and very little due to this library.

**It might be cool to have a component that handles that logic, so one can focus on building fun things:**
(A quick draft covering various states)
<img width="1444" alt="connection" src="https://github.com/buttplugio/buttplug-js/assets/7897006/fbb85a09-a43c-4fe8-8113-c8668b6be6d0">

What is your opinion on this?

**Comment by qdot** [comment]
Yeah this is basically what buttplug playground was supposed to be, and was for a little while. Unfortunately it's been well out of date for quite a while so it doesn't even work any more. While I don't think this sort of thing would work specifically in buttplug-js ('cause frontend ends up being a Whole Thing), I'd happily put links to something like it in our README/app list/etc.

**Comment by stephanbogner** [comment]
Gotcha!
I am thinking how to approach this best. I personally like tinkering with vanilla JS (no react, typescript, etc.) before diving in fully ... but I don't know how far along web components are to create something like this 🤔

PS: Feel free to close this issue as "not doing" or similar.
